repo: openworm/ChannelWorm
shortDescription: "Tools and curated datasets to build quantitative models of C. elegans ion channels"
coordinator: stephen@openworm.org
documentation: "https://channelworm.readthedocs.io/en/latest/"
earnable-badges:
  - "http://www.badgelist.com/OpenWorm/Hodgkin-Huxley-Tutorial-Graduate"
keywords:
  - database
  - data
  - cells
  - channels
languages:
  - python
members:
  - vahidghayoomi@gmail.com
  - milad.jafary@gmail.com
outputs:
  - openworm/muscle_model
  - openworm/CElegansNeuroML
parent:
  - openworm/OpenWorm
tests: true
